### ISSUE TITLE
Error with calling XRotor class on Mac

### ISSUE THREAD

**Issue by zlovering** [daniel-de-vries/xrotor-python#1]
When running the following:
`from xrotor import XRotor
xr = XRotor()`

I get the error
`Traceback (most recent call last):
  File "/Users/zach/Repos/xrotor-python/test.py", line 1, in <module>
    from xrotor import XRotor
  File "/Users/zach/Repos/xrotor-python/xrotor/__init__.py", line 20, in <module>
    from .xrotor import XRotor
  File "/Users/zach/Repos/xrotor-python/xrotor/xrotor.py", line 32, in <module>
    lib_path = glob.glob(os.path.join(here, 'libxrotor.*'))[0]
IndexError: list index out of range`

**Comment by KikeM** [comment]
Hi!

I haven't installed the library yet, but I ran into a similar problem when using xfoil-python.

Check where the compiled files have been created. They might not be where File `"/Users/zach/Repos/xrotor-python/xrotor/xrotor.py", line 30` expects.
